version: '3.8'
x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "prediction"
  DB_USER: "prediction"
  DB_PASSWORD: "prediction"
  DB_HOST: "postgres"
  DB_PORT: 5432
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  SECRET_KEY: "django-insecure-a5z!vaigxg#rxsssr%)2k_)m-i9$#idg*!em5u2s@kuptxli17"


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
      POSTGRES_DB: prediction
    ports:
      - "5432:5432"

  prediction:
    build:
      context: ./prediction
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - prediction

  prediction-app:
    build:
      context: ./prediction-app
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./prediction
    command: celery -A prediction worker --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      <<: *environment-defaults

  celery-beat:
    build:
      context: ./prediction
    command: celery -A prediction beat --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      <<: *environment-defaults


volumes:
  static_volume:
